"""
Mock Orchestrator — right-hand test harness.

Generates TaskMessages with mock fileContent, pushes them to aia-tasks,
then polls aia-status until all responses arrive (or the timeout expires).
Useful for testing the Relay Service in isolation without running the real
CoreBackend + Orchestrator.

Usage:
    # Push one task per agent type for a random document
    python scripts/mock_orchestrator.py

    # Use a specific document ID
    python scripts/mock_orchestrator.py --doc-id abc-123

    # Only push tasks for specific agent types
    python scripts/mock_orchestrator.py --agent-types security technical

    # Send real file content from disk
    python scripts/mock_orchestrator.py --file path/to/document.txt

    # Wait up to 120 s for all results
    python scripts/mock_orchestrator.py --timeout 120
"""

from __future__ import annotations

import argparse
import asyncio
import json
import sys
import time
import uuid
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any

import aiobotocore.session
from dotenv import load_dotenv

# --- resolve root .env and project imports --------------------------------
_ROOT = Path(__file__).resolve().parent.parent
load_dotenv(_ROOT / ".env")

sys.path.insert(0, str(_ROOT))

# Inject evaluation module root so src.* imports resolve (same as relay_service/worker.py)
_EVAL_ROOT = _ROOT / "app" / "agents" / "evaluation"
if str(_EVAL_ROOT) not in sys.path:
    sys.path.insert(0, str(_EVAL_ROOT))

from app.core.config import config  # noqa: E402
from app.models.status_message import StatusMessage  # noqa: E402
from app.models.task_message import TaskMessage  # noqa: E402
from src.handlers.parse import _parse_bytes  # noqa: E402

# --------------------------------------------------------------------------

_DEFAULT_AGENT_TYPES = ["security", "technical"]
_MOCK_FILE_CONTENT = (
    "This is a mock policy document generated by mock_orchestrator.py. "
    "It covers authentication, MFA, data protection, GDPR compliance, "
    "access controls, encryption at rest and in transit, audit trails, "
    "and incident response procedures."
)
_DEFAULT_TIMEOUT = 180  # seconds


@asynccontextmanager
async def _sqs_client():
    session = aiobotocore.session.get_session()
    kwargs: dict[str, Any] = {
        "service_name": "sqs",
        "region_name": config.aws.region,
        "aws_access_key_id": config.aws.access_key_id,
        "aws_secret_access_key": config.aws.secret_access_key,
    }
    if config.aws.endpoint_url:
        kwargs["endpoint_url"] = config.aws.endpoint_url
    async with session.create_client(**kwargs) as client:
        yield client


async def _push_tasks(
    client: Any,
    doc_id: str,
    agent_types: list[str],
    file_content: str,
) -> list[str]:
    """Push one TaskMessage per agent type. Returns list of task_ids."""
    task_ids: list[str] = []
    for agent_type in agent_types:
        task_id = f"{doc_id}_{agent_type}"
        task = TaskMessage(
            task_id=task_id,
            document_id=doc_id,
            agent_type=agent_type,
            template_type="SDA",
            file_content=file_content,
            s3_bucket=config.s3.bucket_name,
            s3_key=f"uploads/{doc_id}.pdf",
        )
        await client.send_message(
            QueueUrl=config.sqs.task_queue_url,
            MessageBody=task.model_dump_json(by_alias=True),
        )
        task_ids.append(task_id)
        print(f"  → pushed  task_id={task_id}  agent_type={agent_type}")
    return task_ids


async def _poll_status(
    client: Any,
    expected_task_ids: set[str],
    timeout: float,
) -> dict[str, StatusMessage]:
    """Poll aia-status until all expected task_ids arrive or timeout expires."""
    results: dict[str, StatusMessage] = {}
    deadline = time.monotonic() + timeout

    while len(results) < len(expected_task_ids):
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            break

        wait = min(20, int(remaining))
        response = await client.receive_message(
            QueueUrl=config.sqs.status_queue_url,
            MaxNumberOfMessages=10,
            WaitTimeSeconds=wait,
            AttributeNames=["All"],
        )

        for raw in response.get("Messages", []):
            try:
                status = StatusMessage.model_validate_json(raw["Body"])
            except Exception as exc:
                print(f"  [warn] could not parse status message: {exc}")
                continue

            if status.task_id not in expected_task_ids:
                # Not ours — leave it visible (do not delete)
                continue

            results[status.task_id] = status
            await client.delete_message(
                QueueUrl=config.sqs.status_queue_url,
                ReceiptHandle=raw["ReceiptHandle"],
            )
            print(
                f"  ✓ received  task_id={status.task_id}  "
                f"error={status.error or 'none'}  "
                f"({len(results)}/{len(expected_task_ids)})"
            )

    return results


def _print_results(results: dict[str, StatusMessage], expected: set[str]) -> None:
    print("\n" + "=" * 60)
    print("RESULTS")
    print("=" * 60)

    for task_id in sorted(expected):
        if task_id not in results:
            print(f"\n  {task_id}  →  [TIMEOUT — no response received]")
            continue

        status = results[task_id]
        print(f"\n  task_id   : {status.task_id}")
        print(f"  agent_type: {status.agent_type}")

        if status.error:
            print(f"  error     : {status.error}")
        else:
            assessments = status.result.get("assessments", [])
            summary = status.result.get("final_summary", {})
            print(f"  assessments : {len(assessments)}")
            for a in assessments[:3]:
                q = str(a.get("Question", ""))[:60]
                print(f"    [{a.get('Rating', '?'):6s}]  {q}…")
            if len(assessments) > 3:
                print(f"    … and {len(assessments) - 3} more")
            if summary:
                interp = str(summary.get("Interpretation", ""))[:100]
                print(f"  interpretation: {interp}")

    missing = expected - set(results)
    print("\n" + "=" * 60)
    print(f"Received {len(results)}/{len(expected)} responses.  Missing: {missing or 'none'}")
    print("=" * 60)


async def run(
    doc_id: str,
    agent_types: list[str],
    file_content: str,
    timeout: float,
) -> None:
    print(
        f"mock_orchestrator: doc_id={doc_id}  "
        f"agent_types={agent_types}  timeout={timeout}s"
    )
    print(f"  task queue  : {config.sqs.task_queue_url}")
    print(f"  status queue: {config.sqs.status_queue_url}")

    async with _sqs_client() as client:
        print("\nPushing tasks…")
        task_ids = await _push_tasks(client, doc_id, agent_types, file_content)
        expected = set(task_ids)

        print(f"\nPolling for {len(expected)} status message(s) (timeout={timeout}s)…")
        results = await _poll_status(client, expected, timeout)

    _print_results(results, expected)


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument(
        "--doc-id",
        default=None,
        help="Document ID to use (default: random UUID)",
    )
    p.add_argument(
        "--agent-types",
        nargs="+",
        default=_DEFAULT_AGENT_TYPES,
        metavar="TYPE",
        help=f"Agent types to push tasks for (default: {_DEFAULT_AGENT_TYPES})",
    )
    p.add_argument(
        "--timeout",
        type=float,
        default=_DEFAULT_TIMEOUT,
        help=f"Seconds to wait for all status responses (default: {_DEFAULT_TIMEOUT})",
    )
    p.add_argument(
        "--file",
        default=None,
        help="Path to a text/PDF file to use as fileContent (default: built-in mock text)",
    )
    return p.parse_args()


if __name__ == "__main__":
    args = _parse_args()

    doc_id = args.doc_id or str(uuid.uuid4())

    if args.file:
        file_path = Path(args.file)
        if not file_path.exists():
            print(f"error: file not found: {args.file}", file=sys.stderr)
            sys.exit(1)
        if file_path.suffix.lower() in (".pdf", ".docx", ".doc"):
            # Parse binary document to text via the evaluation pipeline's Stage 3 parser
            file_bytes = file_path.read_bytes()
            chunks = _parse_bytes(file_bytes, str(file_path), doc_id)
            file_content = "\n\n".join(
                f"## {c['text']}" if c.get("is_heading") else c["text"]
                for c in chunks
            )
            print(f"Using file: {args.file} (parsed {len(chunks)} chunks → {len(file_content)} chars)")
        else:
            file_content = file_path.read_text(encoding="utf-8")
            print(f"Using file: {args.file} ({len(file_content)} chars)")
    else:
        file_content = _MOCK_FILE_CONTENT

    try:
        asyncio.run(
            run(
                doc_id=doc_id,
                agent_types=args.agent_types,
                file_content=file_content,
                timeout=args.timeout,
            )
        )
    except KeyboardInterrupt:
        print("\nmock_orchestrator: interrupted.")
