"""
Mock Agent — left-hand test harness.

Polls aia-tasks, fabricates a StatusMessage for each received task,
and pushes the result to aia-status.  Useful for testing CoreBackend +
Orchestrator in isolation without running the real Relay Service.

Usage:
    python scripts/mock_agent.py                     # run indefinitely, random ratings
    python scripts/mock_agent.py --count 3           # stop after 3 tasks
    python scripts/mock_agent.py --rating Amber      # always return Amber
    python scripts/mock_agent.py --delay 2           # wait 2 s before responding
"""

from __future__ import annotations

import argparse
import asyncio
import json
import random
import sys
import time
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any

import aiobotocore.session
from dotenv import load_dotenv

# --- resolve root .env and project imports --------------------------------
_ROOT = Path(__file__).resolve().parent.parent
load_dotenv(_ROOT / ".env")

sys.path.insert(0, str(_ROOT))

from app.core.config import config  # noqa: E402
from app.models.status_message import StatusMessage  # noqa: E402
from app.models.task_message import TaskMessage  # noqa: E402

# --------------------------------------------------------------------------

_RATINGS = ["Green", "Amber", "Red"]


def _mock_result(agent_type: str, rating: str) -> dict[str, Any]:
    """Build a minimal AgentResult-shaped dict for the given agent_type."""
    assessment = {
        "Question": f"Mock question for {agent_type}",
        "Rating": rating,
        "Comments": f"[mock] Automatically generated {rating} response.",
        "Reference": {"text": "N/A", "url": "https://example.com"},
    }
    return {
        "assessments": [assessment],
        "metadata": {
            "model": "mock",
            "input_tokens": 0,
            "output_tokens": 0,
            "stop_reason": "mock",
        },
        "final_summary": {
            "Interpretation": f"[mock] {rating} — no real analysis performed.",
            "Overall_Comments": "Generated by mock_agent.py test harness.",
        },
    }


@asynccontextmanager
async def _sqs_client():
    session = aiobotocore.session.get_session()
    kwargs: dict[str, Any] = {
        "service_name": "sqs",
        "region_name": config.aws.region,
        "aws_access_key_id": config.aws.access_key_id,
        "aws_secret_access_key": config.aws.secret_access_key,
    }
    if config.aws.endpoint_url:
        kwargs["endpoint_url"] = config.aws.endpoint_url
    async with session.create_client(**kwargs) as client:
        yield client


async def _receive_one(client: Any) -> list[dict[str, str]]:
    response = await client.receive_message(
        QueueUrl=config.sqs.task_queue_url,
        MaxNumberOfMessages=1,
        WaitTimeSeconds=20,
        AttributeNames=["All"],
    )
    return [
        {"body": m["Body"], "receipt_handle": m["ReceiptHandle"]}
        for m in response.get("Messages", [])
    ]


async def run(count: int | None, rating: str | None, delay: float) -> None:
    processed = 0
    print(
        f"mock_agent: polling {config.sqs.task_queue_url}  "
        f"(count={'∞' if count is None else count}, "
        f"rating={'random' if rating is None else rating}, "
        f"delay={delay}s)"
    )

    while count is None or processed < count:
        async with _sqs_client() as client:
            msgs = await _receive_one(client)
            if not msgs:
                print("  [poll] no messages, waiting…")
                continue

            msg = msgs[0]
            task = TaskMessage.model_validate_json(msg["body"])
            chosen_rating = rating or random.choice(_RATINGS)

            print(
                f"  → received task_id={task.task_id}  "
                f"agent_type={task.agent_type}  "
                f"doc_id={task.document_id}"
            )

            if delay > 0:
                print(f"  [delay] sleeping {delay}s…")
                await asyncio.sleep(delay)

            status = StatusMessage(
                task_id=task.task_id,
                document_id=task.document_id,
                agent_type=task.agent_type,
                result=_mock_result(task.agent_type, chosen_rating),
            )

            await client.send_message(
                QueueUrl=config.sqs.status_queue_url,
                MessageBody=status.model_dump_json(by_alias=True),
            )
            await client.delete_message(
                QueueUrl=config.sqs.task_queue_url,
                ReceiptHandle=msg["receipt_handle"],
            )

            processed += 1
            print(
                f"  ✓ published status  rating={chosen_rating}  "
                f"({processed}{'/' + str(count) if count else ''})"
            )

    print(f"mock_agent: done — processed {processed} task(s).")


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--count", type=int, default=None, help="Stop after N tasks (default: run forever)")
    p.add_argument("--rating", choices=_RATINGS, default=None, help="Force a specific rating (default: random)")
    p.add_argument("--delay", type=float, default=0.0, help="Seconds to wait before responding (default: 0)")
    return p.parse_args()


if __name__ == "__main__":
    args = _parse_args()
    try:
        asyncio.run(run(count=args.count, rating=args.rating, delay=args.delay))
    except KeyboardInterrupt:
        print("\nmock_agent: interrupted.")
