"""
Mock Agent — left-hand test harness.

Polls aia-tasks, fabricates a StatusMessage for each received task,
and pushes the result to aia-status.  Useful for testing CoreBackend +
Orchestrator in isolation without running the real Agent Service.

Usage:
    python scripts/mock_agent.py                          # run indefinitely, random ratings
    python scripts/mock_agent.py --count 3                # stop after 3 tasks
    python scripts/mock_agent.py --rating Amber           # always return Amber
    python scripts/mock_agent.py --delay 2                # wait 2 s before responding
    python scripts/mock_agent.py --doc-id <id>            # only handle tasks for that doc
    python scripts/mock_agent.py --doc-id <id> --count 2  # paired run with mock_orchestrator
"""

from __future__ import annotations

import argparse
import asyncio
import random
import sys
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any

import aiobotocore.session
from dotenv import load_dotenv

# --- resolve root .env and project imports --------------------------------
_ROOT = Path(__file__).resolve().parent.parent
load_dotenv(_ROOT / ".env")

sys.path.insert(0, str(_ROOT))

from app.core.config import config  # noqa: E402
from app.models.status_message import StatusMessage  # noqa: E402
from app.models.task_message import TaskMessage  # noqa: E402

# --------------------------------------------------------------------------

_RATINGS = ["Green", "Amber", "Red"]


def _mock_result(agent_type: str, rating: str) -> dict[str, Any]:
    """Build a minimal AgentResult-shaped dict for the given agent_type."""
    assessment = {
        "Question": f"Mock question for {agent_type}",
        "Rating": rating,
        "Comments": f"[mock] Automatically generated {rating} response.",
        "Reference": {"text": "N/A", "url": "https://example.com"},
    }
    return {
        "assessments": [assessment],
        "metadata": {
            "model": "mock",
            "input_tokens": 0,
            "output_tokens": 0,
            "stop_reason": "mock",
        },
        "final_summary": {
            "Interpretation": f"[mock] {rating} — no real analysis performed.",
            "Overall_Comments": "Generated by mock_agent.py test harness.",
        },
    }


@asynccontextmanager
async def _sqs_client():
    session = aiobotocore.session.get_session()
    kwargs: dict[str, Any] = {
        "service_name": "sqs",
        "region_name": config.aws.region,
        "aws_access_key_id": config.aws.access_key_id,
        "aws_secret_access_key": config.aws.secret_access_key,
    }
    if config.aws.session_token:
        kwargs["aws_session_token"] = config.aws.session_token
    if config.aws.endpoint_url:
        kwargs["endpoint_url"] = config.aws.endpoint_url
    async with session.create_client(**kwargs) as client:
        yield client


async def _receive_one(client: Any) -> list[dict[str, str]]:
    response = await client.receive_message(
        QueueUrl=config.sqs.task_queue_url,
        MaxNumberOfMessages=1,
        WaitTimeSeconds=20,
        AttributeNames=["All"],
    )
    return [
        {"body": m["Body"], "receipt_handle": m["ReceiptHandle"]}
        for m in response.get("Messages", [])
    ]


async def run(count: int | None, rating: str | None, delay: float, doc_id: str | None) -> None:
    processed = 0
    filter_desc = f"doc_id={doc_id}" if doc_id else "all docs"
    print(
        f"mock_agent: polling {config.sqs.task_queue_url}  "
        f"(count={'∞' if count is None else count}, "
        f"rating={'random' if rating is None else rating}, "
        f"delay={delay}s, filter={filter_desc})"
    )

    while count is None or processed < count:
        async with _sqs_client() as client:
            msgs = await _receive_one(client)
            if not msgs:
                print("  [poll] no messages, waiting…")
                continue

            msg = msgs[0]
            try:
                task = TaskMessage.model_validate_json(msg["body"])
            except Exception as exc:
                print(f"  [skip] unrecognised message body — {exc}")
                # Leave the message in the queue; it will reappear after visibility timeout.
                continue

            # Skip tasks that belong to a different run without deleting them.
            # They will become visible again after the queue's visibility timeout.
            if doc_id and task.document_id != doc_id:
                print(
                    f"  [skip] task_id={task.task_id}  doc_id={task.document_id}  "
                    f"(waiting for doc_id={doc_id})"
                )
                continue

            chosen_rating = rating or random.choice(_RATINGS)

            print(
                f"  → received  task_id={task.task_id}  "
                f"agent_type={task.agent_type}  "
                f"doc_id={task.document_id}"
            )

            if delay > 0:
                print(f"  [delay] sleeping {delay}s…")
                await asyncio.sleep(delay)

            # Echo the same task_id and document_id back in the StatusMessage
            # so the orchestrator can match the response to its original request.
            status = StatusMessage(
                task_id=task.task_id,
                document_id=task.document_id,
                agent_type=task.agent_type,
                result=_mock_result(task.agent_type, chosen_rating),
            )

            print(
                f"  ← echoing   task_id={status.task_id}  "
                f"doc_id={status.document_id}  "
                f"rating={chosen_rating}"
            )

            await client.send_message(
                QueueUrl=config.sqs.status_queue_url,
                MessageBody=status.model_dump_json(by_alias=True),
            )
            await client.delete_message(
                QueueUrl=config.sqs.task_queue_url,
                ReceiptHandle=msg["receipt_handle"],
            )

            processed += 1
            print(
                f"  ✓ published status  "
                f"({processed}{'/' + str(count) if count else ''})"
            )

    print(f"mock_agent: done — processed {processed} task(s).")


def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--count", type=int, default=None, help="Stop after N tasks (default: run forever)")
    p.add_argument("--rating", choices=_RATINGS, default=None, help="Force a specific rating (default: random)")
    p.add_argument("--delay", type=float, default=0.0, help="Seconds to wait before responding (default: 0)")
    p.add_argument(
        "--doc-id",
        default=None,
        help="Only process tasks whose document_id matches this value; skip others (default: process all)",
    )
    return p.parse_args()


if __name__ == "__main__":
    args = _parse_args()
    try:
        asyncio.run(run(count=args.count, rating=args.rating, delay=args.delay, doc_id=args.doc_id))
    except KeyboardInterrupt:
        print("\nmock_agent: interrupted.")
